/*
One major source of electricity is hydroelectric generation, in which
flowing water is redirected to turn a turbine generator. The power generated by
this water flow is given by this formula: P = ρ × Q × H × g P is the power
generated by the water flow (watts = J/s = kg-m2/s2-1/s). ρ is the water density
(kg/m3) Q is the volume flow rate (m3/s). g is the acceleration caused by
gravity (9.81 m/s2). H is the distance (in m) water falls on its way to the
generator, known as the head.
*/
#include <cmath>
#include <iostream>

using namespace std;

double powerGen(double H, double Q);

int main() {
  // double H = 14.0, Q = 20.0;
  double H = 30.0, Q = 20.0;
  powerGen(H, Q);
  return 0;
}

double powerGen(double H, double Q) {
  double P, p = 997.0, g = 9.81;

  P = p * Q * H * g;
  cout << P << endl;

  return P;
}